[versions]
asciidoctorj = "2.5.10"
asciidoctorjDiagram = "2.2.8"

[libraries]
# Used to help bot retrieve and bump the version of asciidoctor
asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
asciidoctorj-diagram = { module = "org.asciidoctor:asciidoctorj-diagram", version.ref = "asciidoctorjDiagram" }

graalvm-nativeimage-svm = { module = "org.graalvm.nativeimage:svm", version = "22.3.1" }

picocli = { module = "info.picocli:picocli", version = "4.7.3" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version = "4.7.3" }

assertj = { module = "org.assertj:assertj-core", version = "3.24.2" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.9.3" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }

[bundles]


[plugins]
graalvmBuildtoolsNative = { id = "org.graalvm.buildtools.native", version = "0.9.22" }
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "3.3.2" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
download = { id = "de.undercouch.download", version = "5.4.0" }
